title: Synoptix Docs
description: Documentation for Synoptix's platforms and products
theme: just-the-docs

url: https://docs.synoptix.co.uk/assurance

aux_links:
  Synx-Assure Platform: assurance.synoptix.co.uk

#logo: "/assets/images/just-the-docs.png"
